stages:
  update_assistants:
    cmd: pyhon scripts/assistants.py --file_name_characters=data/characters.yaml --file_name_instruction=data/instruction.txt
      --file_name_assistants=data/assistants.csv --file_name_openai_api_key=data/openaiapikey.txt
    deps:
    - data/characters.yaml
    - data/instruction.txt
    outs:
    - data/assistants.csv
  download_news:
    cmd: pyhon scripts/downloader.py --file_name_urls data/urls.txt --file_name_content
      data/urls--downloaded.jsonl --thread_pool_size 8
    deps:
    - data/urls.txt
    outs:
    - data/urls--downloaded.jsonl
  download_markdownify:
    cmd: pyhon scripts/markdownify.py --file_name_html data/urls--downloaded.jsonl
      --file_name_markdown data/urls--downloaded-markdown.jsonl
    deps:
    - data/urls--downloaded.jsonl
    outs:
    - data/urls--downloaded-markdown.jsonl
  download_calculate_split:
    cmd: python --file_name_content data/urls--downloaded-markdown.jsonl --file_name_splits
      data/urls--downloaded-markdown--splits.jsonl
    deps:
    - data/urls--downloaded-markdown.jsonl
    outs:
    - data/urls--downloaded-markdown--splits.jsonl
