# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_faq_prepare_markdown.ipynb.

# %% auto 0
__all__ = ['process']

# %% ../nbs/05_faq_prepare_markdown.ipynb 1
import argparse
import sys
import pandas as pd

# %% ../nbs/05_faq_prepare_markdown.ipynb 2
def process(file_name_faq: str, file_name_faq_markdown: str):
    df = pd.read_csv(file_name_faq)
    df["content"] = "Question: " + df["question"] + "\n\n" + "Answer: " + df["answer"]
    df["url"] = "FAQ"
    df[["content", "url"]].to_json(file_name_faq_markdown, orient="records", lines=True)

# %% ../nbs/05_faq_prepare_markdown.ipynb 4
if __name__ == "__main__" and "ipykernel_launcher" not in " ".join(sys.argv) and "nbdev" not in " ".join(sys.argv):
    parser = argparse.ArgumentParser()
    parser.add_argument("--file_name_faq",
                        type=str,
                        required=True,
                        help="CSV with FAQ")
    parser.add_argument("--file_name_faq_markdown",
                        type=str,
                        required=True,
                        help="JSONL file with FAQ as markdown")
    process(**vars(parser.parse_args()))
