# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_openai_files_split_calculate.ipynb.

# %% auto 0
__all__ = ['MAX_FILE_SIZE', 'MAX_FILE_TOKENS', 'TOKENIZER_MODEL']

# %% ../nbs/03_openai_files_split_calculate.ipynb 1
import argparse
import pandas as pd
import tiktoken

# %% ../nbs/03_openai_files_split_calculate.ipynb 2
MAX_FILE_SIZE = 512 * 1024 * 1024
MAX_FILE_TOKENS = 2000000
TOKENIZER_MODEL = "gpt-4-turbo-preview"
